### ISSUE TITLE
Dispose

### ISSUE THREAD

**Issue by Muldec** [tensor-programming/flutter_bloc_tutorial#3]
Hi !

Quick question : I can't find when the dispose method of the MovieBloc is called. Am I missing something or is it dead code as of today ?

**Comment by lepinay** [comment]
Implementation is bogus
It should use an StateFullWidget instead of an InheritedWidget for the MovieProvider and implement dispose there

See example here: https://stackoverflow.com/questions/51690230/flutter-inheritedwidget-dispose

**Comment by Muldec** [comment]
Thanks ! I figured it out since my original question bbut its good to have a confirmation.
